run:
  skip-dirs:
    - internal/cache # extracted from Go code
    - internal/renameio # extracted from Go code
    - internal/robustio # extracted from Go code

linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
  revive:
    rules:
      - name: package-comments
        disabled: true

linters:
  enable-all: false
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gofmt
    - goimports
    # - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
