---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cluster.sharenamespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnf-nauti
  namespace: nauti-system
  labels:
    app: cnf-nauti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cnf-nauti
  template:
    metadata:
      labels:
        app: cnf-nauti
        router.nauti.io/cnf: "true"
    spec:
      serviceAccountName: octopus
      hostNetwork: false
      containers:
        - name: nri-daemon
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/cnf:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
            privileged: true
          command:
            - ./cnf
          args:
            - --as-hub={{ .Values.cluster.hub }}
            - --cidr={{ .Values.tunnel.cidr }}
            - --as-cluster=false
            - --shared-namespace=syncer-operator
          env:
            - name: NAUTI_CLUSTERID
              value: {{ .Values.cluster.clusterID }}
            - name: NAUTI_ENDPOINT
              value: {{ .Values.tunnel.endpoint }}
            - name: NAUTI_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAUTI_PODNAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 200Mi
      nodeSelector:
        kubernetes.io/os: "linux"