---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cluster.sharenamespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnf-nauti
  namespace: nauti-system
  labels:
    app: cnf-nauti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cnf-nauti
  template:
    metadata:
      labels:
        app: cnf-nauti
        router.nauti.io/cnf: "true"
    spec:
      serviceAccountName: octopus
      hostNetwork: false
      containers:
        - name: nri-daemon
          image: 121.40.102.76:30080/cnf/cnf:v7
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            privileged: true
          command:
            - ./cnf
          args:
            - --as-hub=true
            - --cidr=20.112.0.0/12
            - --as-cluster=false
            - --shared-namespace=syncer-operator
          env:
            - name: NAUTI_CLUSTERID
              value: hub
            - name: NAUTI_ENDPOINT
              value: 172.24.33.2
            - name: NAUTI_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAUTI_PODNAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 200Mi
      nodeSelector:
        kubernetes.io/os: "linux"