apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: crossdns
    component: crossdns
  name: crossdns
  namespace: fleetboard-system
data:
  Corefile: |
    {{ .Values.cluster.zone }}:53 {
        crossdns
        errors
        health
        ready
    }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crossdns
    component: crossdns
  name: crossdns
  namespace: fleetboard-system
spec:
  clusterIP:
  {{- range (lookup "v1" "Service" "kube-system" "").items }}
  {{- if eq (dig "k8s-app" "no-kube-dns" .metadata.labels) "kube-dns" }}
  {{- $last_part := splitList "." (.spec.clusterIP | trimAll "\n") | last | add 1 }}
     {{ concat (slice (splitList "." .spec.clusterIP) 0 3 ) (list $last_part) | join "."}}
  {{- end }}
  {{- end }}
  ports:
    - name: udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: crossdns
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossdns
  namespace: fleetboard-system
  labels:
    app: crossdns
spec:
  selector:
    matchLabels:
      app: crossdns
  template:
    metadata:
      labels:
        app: crossdns
    spec:
      containers:
      - args:
          - -conf
          - /etc/coredns/Corefile
        name: crossdns
        image:  "{{ .Values.image.registry }}/{{ .Values.image.repository }}/crossdns:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: /etc/coredns
            name: config-volume
            readOnly: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: Corefile
                path: Corefile
            name: crossdns
          name: config-volume
