apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dedinic-cni
  namespace: nauti-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dedinic-cni
  template:
    metadata:
      labels:
        app: dedinic-cni
        component: network
        type: infra
    spec:
      initContainers:
        - name: wait-for-ipam-ready
          image: busybox:1.28
          command:
            - sleep
            - "10s"
      containers:
        - name: ep-controller
          command:
            - "/ep-controller"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PARALLEL_IP_ANNOTATION
              value: "nauti.io/ip_address"
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/ep-controller:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
        - args:
            - --v=5
            - --encap-checksum=true
            - --iface=
            - --dpdk-tunnel-iface=br-phy
            - --network-type=geneve
            - --default-interface-name=
            - --logtostderr=false
            - --alsologtostderr=true
            - --log_file=/var/log/dedinic/dedinic-cni.log
            - --log_file_max_size=0
            - --kubelet-dir=/var/lib/kubelet
            - --enable-tproxy=false
            - --ovs-vsctl-concurrency=100
          command:
            - bash
            - /dedinic/start-dedinic.sh
          env:
            - name: NRI_ENABLE
              value: "true"
            - name: ENABLE_SSL
              value: "false"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: MODULES
              value: kube_ovn_fastpath.ko
            - name: RPMS
              value: openvswitch-kmod
            - name: POD_IPS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIPs
            - name: ENABLE_BIND_LOCAL_IP
              value: "true"
            - name: DBUS_SYSTEM_BUS_ADDRESS
              value: unix:path=/host/var/run/dbus/system_bus_socket
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/dedinic:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: dedinic
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /lib/modules
              name: host-modules
              readOnly: true
            - mountPath: /var/lib/kubelet/pods
              name: shared-dir
            - mountPath: /etc/openvswitch
              name: systemid
              readOnly: true
            - mountPath: /etc/cni/net.d
              name: cni-conf
            - mountPath: /run/openvswitch
              mountPropagation: Bidirectional
              name: host-run-ovs
            - mountPath: /run/ovn
              name: host-run-ovn
            - mountPath: /host/var/run/dbus
              mountPropagation: HostToContainer
              name: host-dbus
            - mountPath: /var/run/netns
              mountPropagation: HostToContainer
              name: host-ns
            - mountPath: /var/log/dedinic
              name: dedinic-log
            - mountPath: /var/log/openvswitch
              name: host-log-ovs
            - mountPath: /var/log/ovn
              name: host-log-ovn
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/nri
              mountPropagation: HostToContainer
              name: nrisock
            - name: host-cgroup-root
              mountPath: /opt/dedinic/cgroup
            - name: host-proc
              mountPath: /opt/dedinic/proc
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      securityContext: { }
      serviceAccountName: dedinic-cni
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      volumes:
        - hostPath:
            path: /lib/modules
            type: ""
          name: host-modules
        - hostPath:
            path: /var/lib/kubelet/pods
            type: ""
          name: shared-dir
        - hostPath:
            path: /etc/origin/openvswitch
            type: ""
          name: systemid
        - hostPath:
            path: /run/openvswitch
            type: ""
          name: host-run-ovs
        - hostPath:
            path: /run/ovn
            type: ""
          name: host-run-ovn
        - hostPath:
            path: /etc/cni/net.d
            type: ""
          name: cni-conf
        - hostPath:
            path: /opt/cni/bin
            type: ""
          name: cni-bin
        - hostPath:
            path: /var/run/netns
            type: ""
          name: host-ns
        - hostPath:
            path: /var/run/dbus
            type: ""
          name: host-dbus
        - hostPath:
            path: /var/log/dedinic
            type: ""
          name: dedinic-log
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
        - hostPath:
            path: /var/log/openvswitch
            type: ""
          name: host-log-ovs
        - hostPath:
            path: /var/log/ovn
            type: ""
          name: host-log-ovn
        - hostPath:
            path: /tmp
            type: ""
          name: tmp
        - hostPath:
            path: /usr/local/bin
            type: ""
          name: local-bin
        - hostPath:
            path: /var/run/nri
            type: DirectoryOrCreate
          name: nrisock
        - hostPath:
            path: /sys/fs/cgroup/
            type: ""
          name: host-cgroup-root
        - hostPath:
            path: /proc/
            type: ""
          name: host-proc