---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncer
  namespace: octopus-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nauti:controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: syncer
    namespace: octopus-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer
  namespace: octopus-system
  labels:
    app: syncer
spec:
  selector:
    matchLabels:
      app: syncer
  template:
    metadata:
      labels:
        app: syncer
    spec:
      containers:
        - name: syncer
          image: "{{ .Values.image.repository }}/syncer:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SYNCER_CLUSTERID
              value: {{ .Values.cluster.clusterID }}
            - name: SYNCER_HUBURL
              value: {{ .Values.hub.hubURL }}
            - name: SYNCER_LOCALNAMESPACE
              value: {{ .Values.cluster.localnamespace }}
            - name: SYNCER_SHARENAMESPACE
              value: {{ .Values.cluster.sharenamespace }}
      serviceAccountName: syncer
---
apiVersion: v1
kind: Secret
metadata:
  name: hub-syncer
  namespace: syncer-operator
data:
  apiserver-advertise-url: {{ .Values.hub.hubURL | b64enc }}
  ca.crt: {{ .Values.hub.ca }}
  token: {{ .Values.hub.token }}