---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cluster.localnamespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: nauti-system
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        nauti.io/cnf: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: octopus
          securityContext:
            privileged: false
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/octopus:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OCTOPUS_CLUSTERID
              value: {{ .Values.cluster.clusterID }}
            - name: OCTOPUS_HUBURL
              value: {{ .Values.hub.hubURL }}
            - name: OCTOPUS_BOOTSTRAPTOKEN
              value: {{ .Values.hub.bootstraptoken }}
            {{- if .Values.cluster.ispublic }}
            - name: OCTOPUS_ENDPOINT
              value: {{ .Values.tunnel.endpoint }}
            {{- end }}
            - name: OCTOPUS_SHARENAMESPACE
              value: {{ .Values.cluster.sharenamespace }}
            - name: OCTOPUS_LOCALNAMESPACE
              value: {{ .Values.cluster.localnamespace }}
            - name: OCTOPUS_CIDR
              value: {{ .Values.tunnel.cidr }}
            - name: OCTOPUS_ISHUB
              value: {{ .Values.cluster.hub | quote }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
